### PR TITLE
Update docker scripts

### PR DESCRIPTION
**Pull request by larsk21**
- add separate build script
- use local source files for build
- execute pdflatex several times
- rename output pdf file
- use custom sources.list for apt
- use custom CTAN repo
- use docker ENTRYPOINT
- add export script
- copy source and output files in run script

### CODE REVIEW

**Comment by larsk21** [comment]
@TomWerm could you take a look at this?

**Comment by TomWerm** [comment]
looks great, some minor ideas

build_docker_image.sh 
- all files needed have to be present in the github repository, otherwise a docker hub build wont work (TimeSheetGenerator-v*-jar-with-dependencies.jar seems to be missing)

Dockerfile
- we could try to minimize the number of layers (https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#minimize-the-number-of-layers)

docker/.gitignore
- since the product generates pdf files and uses json files there should be some sort of gitignore for them (an probably a reverse gitignore for the example folder)

docker/build_docker_image.sh
- remove the whole temporary directory?

general
- add a script/parameter to use a built version of the image (and add a deployment method)

**Comment by larsk21** [comment]
Thank you for your response.

**Dockerfile**
Reducing the layers certainly improves the performance, but reduces the readability of the code. Since the image is built once and used afterwards, the build time is not as critical as, for example, the runtime. However I will check if I can join some layers while keeping the file readable.

**.gitignore**
Yes, but those files are not supposed to be placed in the docker directory. The docker run script now supports files anywhere on your file system.

**build_docker_image.sh**
Both ways have pros and cons. Deleting only the files ensures that the script only deletes what it created and the directory structure in my IDE doesn't change when building the docker image.

I will answer to the other points as soon as possible.

**Comment by larsk21** [comment]
> Official Debian and Ubuntu images automatically run `apt-get clean`, so explicit invocation is not required. (https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run)

**Comment by larsk21** [comment]
**build_docker_image.sh** and **general**
For now, we will build the image locally after the Maven build is run, which will generate the searched for `jar` file as described in https://github.com/kit-sdq/TimeSheetGenerator/issues/80. The user then installs the image in their local docker instance and uses the provided run script.

I will update the README file accordingly.

**Pull request merged**
